# Generated by Django 4.2.11 on 2024-04-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
